import React from 'react'


function About(props) {
    return (
        <div style={{color:props.mode==='light'?'black':'white'}}>
            <h1>About Us</h1>
            <p style={{border:"1px solid white",borderRadius:"5px",padding:"20px"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque natus culpa id voluptatem blanditiis laboriosam et vitae ex ipsa accusantium in asperiores harum, ipsum quam ut temporibus veniam doloribus commodi delectus earum quibusdam eaque iure mollitia fugit. Ducimus dolorum mollitia ullam reiciendis consequuntur aspernatur at quis a repudiandae. Repellendus reiciendis ex labore libero excepturi tempora ipsum molestiae perspiciatis sequi? Cupiditate optio id doloremque quod quidem, nulla obcaecati explicabo aspernatur animi maxime laborum! Quam eius ratione dolores vero tempora, earum veniam. Ut recusandae explicabo id omnis odit accusantium exercitationem inventore, aut alias mollitia nobis voluptatibus iure! Doloribus, harum voluptates. Omnis sint repellendus quibusdam ullam molestias eveniet expedita ipsum cupiditate fugiat, quidem mollitia illo suscipit libero cum earum voluptatum quia. Quidem, accusantium quas architecto temporibus consectetur eius minus necessitatibus, doloribus dolore modi corrupti voluptates pariatur tempore ipsam debitis perferendis minima aliquam dignissimos. Magni adipisci deleniti quam nisi molestias natus reiciendis aut ab porro dolorem quasi esse vitae vero, commodi a asperiores? Debitis laudantium accusamus laborum mollitia alias aut perspiciatis reiciendis molestias odit, dolorum facere quasi culpa incidunt magnam laboriosam iste illo iure numquam exercitationem ducimus obcaecati dolores impedit. Non earum alias aperiam recusandae itaque maxime ea voluptatem eos tenetur, pariatur odit, soluta modi excepturi, vel est labore libero eius esse consectetur distinctio nostrum. Doloribus nihil iure amet. Commodi et nulla magnam iusto possimus veritatis! Eligendi aperiam sit assumenda, illum suscipit ipsum nemo tempora, omnis veniam accusantium quaerat! Eos at corrupti explicabo praesentium sunt, nostrum corporis doloremque laudantium ipsum, fugiat provident eveniet! Alias, aspernatur ea. Non odio doloribus beatae ab culpa hic quos atque quibusdam eaque molestias odit et dignissimos incidunt mollitia, dolorem deleniti fugiat pariatur doloremque accusamus molestiae unde ut, perferendis, nemo veniam? Eligendi quod sequi nihil odio nesciunt adipisci voluptatem fugiat fugit corrupti. Laborum libero illo debitis, a eligendi in veritatis voluptates fugiat architecto repellendus, ratione autem maiores. Cum quisquam, facilis sit ex laudantium omnis corrupti illum molestiae ullam id ipsa quam assumenda error, earum quod saepe consectetur? Officia deserunt repellat id deleniti commodi ea tenetur totam ex velit cupiditate, fugiat sit quibusdam delectus.</p>
        </div>
    )
}

export default About
